apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../../../../istio/oidc-authservice/base/envoy-filter.yaml
- ../../../../istio/oidc-authservice/base/pvc.yaml
- ../../../../istio/oidc-authservice/base/service.yaml
- ../../../../istio/oidc-authservice/base/statefulset.yaml
- ../../../../istio/oidc-authservice/overlays/application/application.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: oidc-authservice-parameters
  envs:
  - params.env
configurations:
- params.yaml
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: oidc-authservice-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/kubeflow/oidc-authservice
  newTag: 28c59ef
- name: busybox
  newTag: "latest"
  newName: busybox
patchesStrategicMerge:
- statefulset-patch.yaml
