apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../../../../istio/oidc-authservice/base/envoy-filter.yaml
- ../../../../istio/oidc-authservice/base/pvc.yaml
- ../../../../istio/oidc-authservice/base/service.yaml
- ../../../../istio/oidc-authservice/base/statefulset.yaml
- ../../../../istio/oidc-authservice/overlays/application/application.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: oidc-authservice-config
  envs:
  - params.env
configurations:
- params.yaml
vars:
- name: client_id
  objref:
    kind: ConfigMap
    name: oidc-authservice-config
    apiVersion: v1
  fieldref:
    fieldpath: data.client_id
- name: oidc_provider
  objref:
    kind: ConfigMap
    name: oidc-authservice-config
    apiVersion: v1
  fieldref:
    fieldpath: data.oidc_provider
- name: oidc_redirect_uri
  objref:
    kind: ConfigMap
    name: oidc-authservice-config
    apiVersion: v1
  fieldref:
    fieldpath: data.oidc_redirect_uri
- name: oidc_auth_url
  objref:
    kind: ConfigMap
    name: oidc-authservice-config
    apiVersion: v1
  fieldref:
    fieldpath: data.oidc_auth_url
- name: application_secret
  objref:
    kind: ConfigMap
    name: oidc-authservice-config
    apiVersion: v1
  fieldref:
    fieldpath: data.application_secret
- name: skip_auth_uri
  objref:
    kind: ConfigMap
    name: oidc-authservice-config
    apiVersion: v1
  fieldref:
    fieldpath: data.skip_auth_uri
- name: namespace
  objref:
    kind: ConfigMap
    name: oidc-authservice-config
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/kubeflow/oidc-authservice
  newTag: 28c59ef
- name: busybox
  newTag: "latest"
  newName: busybox
patchesStrategicMerge:
- statefulset-patch.yaml
