apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- statefulset.yaml
- envoy-filter.yaml
- pvc.yaml

namespace: istio-system

configMapGenerator:
- name: oidc-authservice-parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: oidc-authservice-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
images:
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: gcr.io/arrikto/kubeflow/oidc-authservice
  newTag: 28c59ef
