apiVersion: v1alpha1
kind: ConfigMapMerge
metadata:
  name: oidc-authservice-merge
  annotations:
    config.kubernetes.io/function: |
      container:
        image: adrian555/fn:latest
spec:
  configMaps:
  - name: oidc-authservice-config
    behavior: merge
    literals:
    - application_secret="<the-client-secret-of-oidc-service>"
